import type { Metadata } from "next";
import { Header } from "@/app/ui/landing/header/header";
import { Footer } from "@/app/ui/landing/footer/footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Joshua Shipping Logistics",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
          <main>
            {children}
          </main>
      </body>
    </html>
  );
}